version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: container_name_web
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: web
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini

  webserever:
    image: nginx:alpine
    container_name: container_name_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7777:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  database:
    image: mysql:8.0.25
    container_name: container_name_mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    tty: true
    ports:
      - "7776:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database
      MYSQL_ROOT_PASSWORD: database
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container_name_phpmyadmin
    environment:
      PMA_HOST: root
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_PORT: 3306
    ports:
      - 7760:80