version: '3.9'

services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "1337:80"
        volumes:
            - ./:/var/www
        tty: true
        depends_on:
            -   php-fpm
    php-fpm:
        tty: true
        build:
            context: docker/php-fpm
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    php-cli:
        build:
            context: docker/php-cli
        volumes:
            - ./:/var/www
    database:
        image: mysql:8.0.28
        ports:
            - "3306:3306"
        container_name: database
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: database
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            -   dbdata:/var/lib/mysql
            - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: root
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_PORT: 3306
        ports:
            - "1488:80"
#Volumes
volumes:
    dbdata:
        driver: local